---
title: "Information Content in Color Images"
author: "Ulilé Indeque and Alejandro C. Frery"
date: "11/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The central hypothesis is that the "ideal" color image has certain properties in the CIELAB space.
This ideal image has "maximum realizable color information" (MRCI).

The MRCI consists in having uniform distribution in the CIELAB space.
The "non-conformity" to MRCI is a measure of the distance between the distributions of the observed image and the MRCI image.
We can measure such distances in may ways, for instance with the Kullback-Leibler divergence.

The authors obtain an empirical version of the distribution of an MRCI image by sampling points uniformly in the $[L^* , a^* , b^*]$ set, i.e., by sampling uniformly in $[0,100]\times[−200,200]\times [−200,200]$, and then mapping these points to valid points in the $(R,G,B)$ space $[0,1]^3$.
Only the valid $(R,G,B)$ points are considered.

The first step of our study will consist in obtaining the empirical distribution of an MRCI image in this way.
This empirical distribution can be described by a 3D histogram.
Parameters to define:

* Size of the MRCI, say $m\times m$.
* Number of samples in the $(R,G,B)$ space
* Kind of histogram

The second step requires defining the distance measure between the distribution of colors of the actual image and the MRCI.
We may try, at least, two: Kullback-Leibler **distance** (not divergence), and Hellinger distance.

The third step consists in defining patches of size $m\times m$ of the actual image in all the color decompositions, and measuring their distances to the MRCI.

Finally, we will show selected patches before and after improving their contrast by matching the $L^*$ histogram with the MRCI one.


