---
title: "Acompanhamento"
author: "Professor Alejandro & Ulile"
date: "23/11/2020"
output: html_document
---

## Introdução

O presente trabalho destina-se a obtenção das medidas de distância entre duas distribuições ou melhor, entre uma imagem "ideal" fixa e outra simulada. Usando histogramas dos dados, existem diferentes métricas que podem ser utilizados. Neste trabalho, a primeira parte objetiva-se à obtenção dos resultados utilizando a divergência "Kullback-Leibler" em imagens no espaço "CIE-lab.

## Etapas 
 
**1 - Obter imagem preparada usando espaço "CIE-lab"**  
    R: para obter imagem, usamos a função "loadImage()" setando o parâmetro CIELab = T e ref.white = "D5".  
    
**2 - Observar a distribuição dos pixels**  
    R: dentre diversas funções para ver a distriuição dos pixels, optamos por usar "plotPixels()" setando o     parâmetro color.space = "lab", mantendo os parâmetros do passo anterior. 
    
**3 - Histograma em 3D**  
    R: etapa fundamental para obter resultados mais consistente. Para isso, usamos "getLabHist()" com o         parâmetro bins = x, em que x foi variando de $[1, 4]$. Passo não concluido ainda, faltando a definição do bins mais preciso. !!!??? 
    
**4 - Aplicação de métrica**  
    R: usamos Kullback-Leibler para obter similaridade entre P e Q. Passo em análise!!!??? 